### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by viks2015** [rguitar96/twitter_heatmap#1]
I using Ubuntu and getting this error 

Traceback (most recent call last):
  File "twitter_heatmap.py", line 69, in <module>
    twitterStream.filter(locations=region)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 450, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 364, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 297, in _run
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 266, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 327, in _read_loop
    self._data(next_status_obj)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 300, in _data
    if self.listener.on_data(data) is False:
  File "twitter_heatmap.py", line 52, in on_data
    tweet = '%s|%s|%s|%s\n' % (user,location,created,text)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)

**Comment by rguitar96** [comment]
Sorry for the late response, but I suspect that the error is because of using Python 2.x. This little project runs on Python 3.x.
